create table project (
	id INT,
	name VARCHAR(50),
	service_provider_id INT,
	code VARCHAR(50),
	sector VARCHAR(50),
	app_version VARCHAR(50)
);
insert into project (id, name, service_provider_id, code, sector, app_version) values (1, 'Biodex', 1, 'FHB', 'Finance', '6.58');
insert into project (id, name, service_provider_id, code, sector, app_version) values (2, 'Voyatouch', 2, 'HYND', 'n/a', '9.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (3, 'Overhold', 3, 'PZN', 'Finance', '0.91');
insert into project (id, name, service_provider_id, code, sector, app_version) values (4, 'Voyatouch', 4, 'AHH', 'Finance', '2.6.0');
insert into project (id, name, service_provider_id, code, sector, app_version) values (5, 'Zoolab', 5, 'OVBC', 'Finance', '7.56');
insert into project (id, name, service_provider_id, code, sector, app_version) values (6, 'Latlux', 6, 'PEBO', 'Finance', '2.86');
insert into project (id, name, service_provider_id, code, sector, app_version) values (7, 'Andalax', 7, 'NATR', 'Health Care', '6.46');
insert into project (id, name, service_provider_id, code, sector, app_version) values (8, 'Tin', 8, 'OUT', 'Consumer Services', '9.5');
insert into project (id, name, service_provider_id, code, sector, app_version) values (9, 'Job', 9, 'JELD', 'Basic Industries', '9.2.4');
insert into project (id, name, service_provider_id, code, sector, app_version) values (10, 'Zontrax', 10, 'CHA', 'Public Utilities', '0.6.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (11, 'Andalax', 11, 'MTBC', 'Technology', '0.70');
insert into project (id, name, service_provider_id, code, sector, app_version) values (12, 'Asoka', 12, 'HRG', 'Miscellaneous', '9.72');
insert into project (id, name, service_provider_id, code, sector, app_version) values (13, 'Sonair', 13, 'BGX', 'n/a', '3.30');
insert into project (id, name, service_provider_id, code, sector, app_version) values (14, 'Overhold', 14, 'ORBK', 'Capital Goods', '0.8.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (15, 'Ronstring', 15, 'MCHI', 'n/a', '2.9');
insert into project (id, name, service_provider_id, code, sector, app_version) values (16, 'Y-find', 16, 'TCON', 'Health Care', '0.8.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (17, 'Stronghold', 17, 'AFGE', 'Finance', '3.70');
insert into project (id, name, service_provider_id, code, sector, app_version) values (18, 'Transcof', 18, 'CXDC', 'Capital Goods', '5.90');
insert into project (id, name, service_provider_id, code, sector, app_version) values (19, 'Bitchip', 19, 'NKX', 'n/a', '3.06');
insert into project (id, name, service_provider_id, code, sector, app_version) values (20, 'Voltsillam', 20, 'PSA^', 'n/a', '0.8.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (21, 'Zamit', 21, 'JMU', 'Technology', '5.86');
insert into project (id, name, service_provider_id, code, sector, app_version) values (22, 'Fintone', 22, 'BPOP', 'Finance', '0.5.1');
insert into project (id, name, service_provider_id, code, sector, app_version) values (23, 'Opela', 23, 'LCAH', 'Finance', '0.94');
insert into project (id, name, service_provider_id, code, sector, app_version) values (24, 'Wrapsafe', 24, 'PCN', 'n/a', '0.1.5');
insert into project (id, name, service_provider_id, code, sector, app_version) values (25, 'Duobam', 25, 'IPCI', 'Health Care', '5.21');
insert into project (id, name, service_provider_id, code, sector, app_version) values (26, 'Gembucket', 26, 'LIND', 'Consumer Services', '1.87');
insert into project (id, name, service_provider_id, code, sector, app_version) values (27, 'Tempsoft', 27, 'ABAC', 'Consumer Non-Durables', '5.1.5');
insert into project (id, name, service_provider_id, code, sector, app_version) values (28, 'Aerified', 28, 'PLYA', 'Consumer Services', '0.76');
insert into project (id, name, service_provider_id, code, sector, app_version) values (29, 'Subin', 29, 'OMED', 'Health Care', '5.67');
insert into project (id, name, service_provider_id, code, sector, app_version) values (30, 'Bamity', 30, 'DWAS', 'n/a', '0.37');
insert into project (id, name, service_provider_id, code, sector, app_version) values (31, 'Temp', 31, 'COF', 'Finance', '0.1.7');
insert into project (id, name, service_provider_id, code, sector, app_version) values (32, 'Regrant', 32, 'CONE', 'Consumer Services', '2.99');
insert into project (id, name, service_provider_id, code, sector, app_version) values (33, 'Y-find', 33, 'INN^', 'n/a', '0.7.5');
insert into project (id, name, service_provider_id, code, sector, app_version) values (34, 'Zamit', 34, 'APLE', 'Consumer Services', '0.74');
insert into project (id, name, service_provider_id, code, sector, app_version) values (35, 'Viva', 35, 'ECCZ', 'n/a', '6.7.0');
insert into project (id, name, service_provider_id, code, sector, app_version) values (36, 'Konklab', 36, 'LAMR', 'Consumer Services', '0.71');
insert into project (id, name, service_provider_id, code, sector, app_version) values (37, 'Otcom', 37, 'PLD', 'Consumer Services', '7.12');
insert into project (id, name, service_provider_id, code, sector, app_version) values (38, 'Toughjoyfax', 38, 'XTLB', 'Health Care', '3.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (39, 'Bigtax', 39, 'DX^B', 'n/a', '0.4.0');
insert into project (id, name, service_provider_id, code, sector, app_version) values (40, 'Stim', 40, 'SITE', 'Consumer Non-Durables', '7.6');
insert into project (id, name, service_provider_id, code, sector, app_version) values (41, 'Quo Lux', 41, 'GLBS', 'Transportation', '8.2.1');
insert into project (id, name, service_provider_id, code, sector, app_version) values (42, 'Zathin', 42, 'FALC', 'Technology', '0.5.6');
insert into project (id, name, service_provider_id, code, sector, app_version) values (43, 'Lotstring', 43, 'UIHC', 'Finance', '0.42');
insert into project (id, name, service_provider_id, code, sector, app_version) values (44, 'Flexidy', 44, 'BOJA', 'Consumer Services', '5.9.0');
insert into project (id, name, service_provider_id, code, sector, app_version) values (45, 'Prodder', 45, 'MBTF', 'Finance', '3.85');
insert into project (id, name, service_provider_id, code, sector, app_version) values (46, 'Greenlam', 46, 'TDOC', 'Health Care', '9.4');
insert into project (id, name, service_provider_id, code, sector, app_version) values (47, 'Hatity', 47, 'WMT', 'Consumer Services', '0.1.0');
insert into project (id, name, service_provider_id, code, sector, app_version) values (48, 'Matsoft', 48, 'STX', 'Technology', '9.5');
insert into project (id, name, service_provider_id, code, sector, app_version) values (49, 'Fixflex', 49, 'LILA', 'Consumer Services', '7.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (50, 'Flowdesk', 50, 'CII', 'n/a', '0.5.9');
insert into project (id, name, service_provider_id, code, sector, app_version) values (51, 'Kanlam', 51, 'NSS', 'Energy', '1.3.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (52, 'Sub-Ex', 52, 'CSRA', 'Technology', '7.2.8');
insert into project (id, name, service_provider_id, code, sector, app_version) values (53, 'Treeflex', 53, 'GULF', 'n/a', '2.8.1');
insert into project (id, name, service_provider_id, code, sector, app_version) values (54, 'Temp', 54, 'SUPV', 'Finance', '0.31');
insert into project (id, name, service_provider_id, code, sector, app_version) values (55, 'Gembucket', 55, 'UNXL', 'Capital Goods', '6.2.1');
insert into project (id, name, service_provider_id, code, sector, app_version) values (56, 'Namfix', 56, 'FSIC', 'n/a', '0.1.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (57, 'Bigtax', 57, 'CLS', 'Technology', '7.3.0');
insert into project (id, name, service_provider_id, code, sector, app_version) values (58, 'Pannier', 58, 'HYT', 'n/a', '7.8');
insert into project (id, name, service_provider_id, code, sector, app_version) values (59, 'Aerified', 59, 'CCU', 'Consumer Non-Durables', '0.18');
insert into project (id, name, service_provider_id, code, sector, app_version) values (60, 'Stronghold', 60, 'CBO', 'n/a', '8.45');
insert into project (id, name, service_provider_id, code, sector, app_version) values (61, 'Subin', 61, 'RCMT', 'Technology', '0.4.4');
insert into project (id, name, service_provider_id, code, sector, app_version) values (62, 'Treeflex', 62, 'MLNX', 'Technology', '3.6');
insert into project (id, name, service_provider_id, code, sector, app_version) values (63, 'Zoolab', 63, 'WFC^', 'n/a', '3.8');
insert into project (id, name, service_provider_id, code, sector, app_version) values (64, 'Home Ing', 64, 'QINC', 'n/a', '5.34');
insert into project (id, name, service_provider_id, code, sector, app_version) values (65, 'Alpha', 65, 'SUPN', 'Health Care', '5.56');
insert into project (id, name, service_provider_id, code, sector, app_version) values (66, 'Namfix', 66, 'CHT', 'Public Utilities', '0.10');
insert into project (id, name, service_provider_id, code, sector, app_version) values (67, 'Matsoft', 67, 'NSA', 'Consumer Services', '0.12');
insert into project (id, name, service_provider_id, code, sector, app_version) values (68, 'Voyatouch', 68, 'PLUG', 'Energy', '0.9.6');
insert into project (id, name, service_provider_id, code, sector, app_version) values (69, 'Bytecard', 69, 'SYBT', 'Finance', '8.89');
insert into project (id, name, service_provider_id, code, sector, app_version) values (70, 'Quo Lux', 70, 'CORE', 'Consumer Non-Durables', '6.3.6');
insert into project (id, name, service_provider_id, code, sector, app_version) values (71, 'Treeflex', 71, 'CLIR', 'Capital Goods', '6.1.1');
insert into project (id, name, service_provider_id, code, sector, app_version) values (72, 'Span', 72, 'MSA', 'Health Care', '5.7');
insert into project (id, name, service_provider_id, code, sector, app_version) values (73, 'Stringtough', 73, 'MMLP', 'Energy', '1.7.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (74, 'Span', 74, 'EXLS', 'Miscellaneous', '0.9.7');
insert into project (id, name, service_provider_id, code, sector, app_version) values (75, 'Asoka', 75, 'ITCI', 'Health Care', '2.9');
insert into project (id, name, service_provider_id, code, sector, app_version) values (76, 'Keylex', 76, 'CDL', 'n/a', '6.44');
insert into project (id, name, service_provider_id, code, sector, app_version) values (77, 'Holdlamis', 77, 'AERI', 'Health Care', '0.83');
insert into project (id, name, service_provider_id, code, sector, app_version) values (78, 'Cardify', 78, 'MNK', 'Health Care', '0.2.8');
insert into project (id, name, service_provider_id, code, sector, app_version) values (79, 'Duobam', 79, 'EHI', 'n/a', '5.36');
insert into project (id, name, service_provider_id, code, sector, app_version) values (80, 'Fintone', 80, 'NEOG', 'Health Care', '1.19');
insert into project (id, name, service_provider_id, code, sector, app_version) values (81, 'Subin', 81, 'LII', 'Capital Goods', '3.85');
insert into project (id, name, service_provider_id, code, sector, app_version) values (82, 'Flowdesk', 82, 'LBIX', 'Consumer Non-Durables', '0.42');
insert into project (id, name, service_provider_id, code, sector, app_version) values (83, 'Domainer', 83, 'GIB', 'Consumer Services', '2.3.9');
insert into project (id, name, service_provider_id, code, sector, app_version) values (84, 'Stronghold', 84, 'WABC', 'Finance', '0.6.6');
insert into project (id, name, service_provider_id, code, sector, app_version) values (85, 'Greenlam', 85, 'AHL^', 'n/a', '1.5');
insert into project (id, name, service_provider_id, code, sector, app_version) values (86, 'Asoka', 86, 'LGND', 'Health Care', '0.3.9');
insert into project (id, name, service_provider_id, code, sector, app_version) values (87, 'Transcof', 87, 'PVG', 'Basic Industries', '0.28');
insert into project (id, name, service_provider_id, code, sector, app_version) values (88, 'Tin', 88, 'USCR', 'Capital Goods', '6.6');
insert into project (id, name, service_provider_id, code, sector, app_version) values (89, 'Konklab', 89, 'BABA', 'Miscellaneous', '0.59');
insert into project (id, name, service_provider_id, code, sector, app_version) values (90, 'Zontrax', 90, 'ADUS', 'Health Care', '2.9');
insert into project (id, name, service_provider_id, code, sector, app_version) values (91, 'Konklab', 91, 'TILE', 'Consumer Durables', '0.4.4');
insert into project (id, name, service_provider_id, code, sector, app_version) values (92, 'Sonsing', 92, 'FLR', 'Basic Industries', '0.34');
insert into project (id, name, service_provider_id, code, sector, app_version) values (93, 'Hatity', 93, 'IMRN', 'Health Care', '0.29');
insert into project (id, name, service_provider_id, code, sector, app_version) values (94, 'Quo Lux', 94, 'TTWO', 'Technology', '5.5.6');
insert into project (id, name, service_provider_id, code, sector, app_version) values (95, 'Zamit', 95, 'LARK', 'Finance', '5.80');
insert into project (id, name, service_provider_id, code, sector, app_version) values (96, 'Zamit', 96, 'ELU', 'Public Utilities', '2.76');
insert into project (id, name, service_provider_id, code, sector, app_version) values (97, 'Bitchip', 97, 'LCUT', 'Capital Goods', '2.0.4');
insert into project (id, name, service_provider_id, code, sector, app_version) values (98, 'Bytecard', 98, 'TRPX', 'Health Care', '4.0');
insert into project (id, name, service_provider_id, code, sector, app_version) values (99, 'Home Ing', 99, 'JBT', 'Technology', '1.0.9');
insert into project (id, name, service_provider_id, code, sector, app_version) values (100, 'Latlux', 100, 'WSTL', 'Public Utilities', '0.16');
insert into project (id, name, service_provider_id, code, sector, app_version) values (101, 'Hatity', 1, 'FORR', 'Consumer Services', '0.32');
insert into project (id, name, service_provider_id, code, sector, app_version) values (102, 'Matsoft', 2, 'HCAP', 'n/a', '1.84');
insert into project (id, name, service_provider_id, code, sector, app_version) values (103, 'Veribet', 3, 'HBAN', 'Finance', '5.1.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (104, 'Cookley', 4, 'PFMT', 'Consumer Services', '5.8.1');
insert into project (id, name, service_provider_id, code, sector, app_version) values (105, 'Opela', 5, 'TBI', 'Technology', '5.07');
insert into project (id, name, service_provider_id, code, sector, app_version) values (106, 'Transcof', 6, 'ESG', 'n/a', '2.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (107, 'Job', 7, 'PGJ', 'n/a', '3.7.8');
insert into project (id, name, service_provider_id, code, sector, app_version) values (108, 'Tempsoft', 8, 'TANH', 'Basic Industries', '2.2.4');
insert into project (id, name, service_provider_id, code, sector, app_version) values (109, 'Y-find', 9, 'DTV', 'Public Utilities', '0.81');
insert into project (id, name, service_provider_id, code, sector, app_version) values (110, 'Tin', 10, 'NGVT', 'Basic Industries', '4.4.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (111, 'Zaam-Dox', 11, 'OSTK', 'Consumer Services', '0.7.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (112, 'Subin', 12, 'TWTR', 'Technology', '5.7');
insert into project (id, name, service_provider_id, code, sector, app_version) values (113, 'Wrapsafe', 13, 'LXFR', 'Basic Industries', '0.3.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (114, 'Asoka', 14, 'CLGX', 'Technology', '6.7');
insert into project (id, name, service_provider_id, code, sector, app_version) values (115, 'Konklux', 15, 'UMBF', 'Finance', '8.1');
insert into project (id, name, service_provider_id, code, sector, app_version) values (116, 'Alpha', 16, 'RIBT', 'Consumer Non-Durables', '0.56');
insert into project (id, name, service_provider_id, code, sector, app_version) values (117, 'Prodder', 17, 'FEMS', 'n/a', '0.8.7');
insert into project (id, name, service_provider_id, code, sector, app_version) values (118, 'Viva', 18, 'PPP', 'Basic Industries', '0.65');
insert into project (id, name, service_provider_id, code, sector, app_version) values (119, 'Veribet', 19, 'OSBC', 'Finance', '0.88');
insert into project (id, name, service_provider_id, code, sector, app_version) values (120, 'Wrapsafe', 20, 'EFX', 'Finance', '4.6.8');
insert into project (id, name, service_provider_id, code, sector, app_version) values (121, 'Pannier', 21, 'SMED', 'Basic Industries', '0.1.6');
insert into project (id, name, service_provider_id, code, sector, app_version) values (122, 'Stringtough', 22, 'LKSD', 'Miscellaneous', '0.2.4');
insert into project (id, name, service_provider_id, code, sector, app_version) values (123, 'Pannier', 23, 'CBFV', 'Finance', '2.92');
insert into project (id, name, service_provider_id, code, sector, app_version) values (124, 'Regrant', 24, 'CCUR', 'Technology', '0.71');
insert into project (id, name, service_provider_id, code, sector, app_version) values (125, 'Otcom', 25, 'VIRT', 'Finance', '0.77');
insert into project (id, name, service_provider_id, code, sector, app_version) values (126, 'Ventosanzap', 26, 'FELE', 'Consumer Durables', '0.38');
insert into project (id, name, service_provider_id, code, sector, app_version) values (127, 'Sub-Ex', 27, 'HNNA', 'Finance', '7.43');
insert into project (id, name, service_provider_id, code, sector, app_version) values (128, 'Duobam', 28, 'UPL', 'Energy', '6.9.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (129, 'Duobam', 29, 'TFX', 'Health Care', '6.2.6');
insert into project (id, name, service_provider_id, code, sector, app_version) values (130, 'Viva', 30, 'PSA^', 'Consumer Services', '0.2.8');
insert into project (id, name, service_provider_id, code, sector, app_version) values (131, 'Holdlamis', 31, 'VWOB', 'n/a', '4.95');
insert into project (id, name, service_provider_id, code, sector, app_version) values (132, 'Voyatouch', 32, 'LCA', 'Finance', '0.7.5');
insert into project (id, name, service_provider_id, code, sector, app_version) values (133, 'Job', 33, 'GYC', 'Finance', '9.8');
insert into project (id, name, service_provider_id, code, sector, app_version) values (134, 'Otcom', 34, 'HTZ', 'Consumer Services', '9.4');
insert into project (id, name, service_provider_id, code, sector, app_version) values (135, 'Quo Lux', 35, 'PCBK', 'Finance', '8.58');
insert into project (id, name, service_provider_id, code, sector, app_version) values (136, 'Zathin', 36, 'K', 'Consumer Non-Durables', '0.1.1');
insert into project (id, name, service_provider_id, code, sector, app_version) values (137, 'Bitwolf', 37, 'RAS', 'Consumer Services', '0.50');
insert into project (id, name, service_provider_id, code, sector, app_version) values (138, 'Matsoft', 38, 'NFLX', 'Consumer Services', '0.84');
insert into project (id, name, service_provider_id, code, sector, app_version) values (139, 'Latlux', 39, 'PMT^', 'n/a', '7.33');
insert into project (id, name, service_provider_id, code, sector, app_version) values (140, 'Regrant', 40, 'RMR', 'Consumer Services', '9.15');
insert into project (id, name, service_provider_id, code, sector, app_version) values (141, 'Lotstring', 41, 'CLD', 'Energy', '0.6.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (142, 'Solarbreeze', 42, 'MOGL', 'n/a', '0.4.6');
insert into project (id, name, service_provider_id, code, sector, app_version) values (143, 'Voyatouch', 43, 'HIX', 'n/a', '9.4.7');
insert into project (id, name, service_provider_id, code, sector, app_version) values (144, 'Cardify', 44, 'CDE', 'Basic Industries', '2.8');
insert into project (id, name, service_provider_id, code, sector, app_version) values (145, 'Job', 45, 'OXLC', 'n/a', '9.9');
insert into project (id, name, service_provider_id, code, sector, app_version) values (146, 'Tampflex', 46, 'HRC', 'Health Care', '4.8');
insert into project (id, name, service_provider_id, code, sector, app_version) values (147, 'Prodder', 47, 'NEWT', 'n/a', '0.9.7');
insert into project (id, name, service_provider_id, code, sector, app_version) values (148, 'Bytecard', 48, 'TSNU', 'Consumer Non-Durables', '4.0.7');
insert into project (id, name, service_provider_id, code, sector, app_version) values (149, 'Daltfresh', 49, 'CBL^', 'n/a', '4.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (150, 'Zontrax', 50, 'DSPG', 'Technology', '0.8.6');
insert into project (id, name, service_provider_id, code, sector, app_version) values (151, 'Zamit', 51, 'NVCN', 'Health Care', '7.7.7');
insert into project (id, name, service_provider_id, code, sector, app_version) values (152, 'Holdlamis', 52, 'OGXI', 'Health Care', '9.42');
insert into project (id, name, service_provider_id, code, sector, app_version) values (153, 'Greenlam', 53, 'IVR', 'Consumer Services', '1.6.6');
insert into project (id, name, service_provider_id, code, sector, app_version) values (154, 'Flowdesk', 54, 'TUES', 'Consumer Services', '4.32');
insert into project (id, name, service_provider_id, code, sector, app_version) values (155, 'Veribet', 55, 'PKI', 'Capital Goods', '8.00');
insert into project (id, name, service_provider_id, code, sector, app_version) values (156, 'Ronstring', 56, 'SUMR', 'Consumer Durables', '5.5.4');
insert into project (id, name, service_provider_id, code, sector, app_version) values (157, 'Job', 57, 'FANH', 'Finance', '3.53');
insert into project (id, name, service_provider_id, code, sector, app_version) values (158, 'Otcom', 58, 'STN', 'Consumer Services', '0.79');
insert into project (id, name, service_provider_id, code, sector, app_version) values (159, 'Regrant', 59, 'XBIO', 'Health Care', '0.17');
insert into project (id, name, service_provider_id, code, sector, app_version) values (160, 'Overhold', 60, 'TOO^', 'n/a', '8.4');
insert into project (id, name, service_provider_id, code, sector, app_version) values (161, 'Zaam-Dox', 61, 'GEC', 'Technology', '0.9.5');
insert into project (id, name, service_provider_id, code, sector, app_version) values (162, 'Matsoft', 62, 'GHY', 'n/a', '0.4.8');
insert into project (id, name, service_provider_id, code, sector, app_version) values (163, 'Greenlam', 63, 'SNSS', 'Health Care', '0.35');
insert into project (id, name, service_provider_id, code, sector, app_version) values (164, 'It', 64, 'AMRB', 'Finance', '0.27');
insert into project (id, name, service_provider_id, code, sector, app_version) values (165, 'Lotstring', 65, 'NBL', 'Energy', '5.0');
insert into project (id, name, service_provider_id, code, sector, app_version) values (166, 'Vagram', 66, 'NGL', 'Energy', '0.9.6');
insert into project (id, name, service_provider_id, code, sector, app_version) values (167, 'Sonair', 67, 'GSM', 'Capital Goods', '0.4.1');
insert into project (id, name, service_provider_id, code, sector, app_version) values (168, 'Pannier', 68, 'HBAN', 'Finance', '3.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (169, 'Fintone', 69, 'RBS^', 'Finance', '6.21');
insert into project (id, name, service_provider_id, code, sector, app_version) values (170, 'It', 70, 'TCF^', 'n/a', '0.29');
insert into project (id, name, service_provider_id, code, sector, app_version) values (171, 'Stim', 71, 'GLOP', 'n/a', '8.27');
insert into project (id, name, service_provider_id, code, sector, app_version) values (172, 'Holdlamis', 72, 'JHB', 'n/a', '5.90');
insert into project (id, name, service_provider_id, code, sector, app_version) values (173, 'Alphazap', 73, 'BAC^', 'n/a', '6.4');
insert into project (id, name, service_provider_id, code, sector, app_version) values (174, 'Andalax', 74, 'TSO', 'Energy', '3.8.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (175, 'Hatity', 75, 'ANIP', 'Health Care', '9.21');
insert into project (id, name, service_provider_id, code, sector, app_version) values (176, 'Zontrax', 76, 'MED', 'Consumer Non-Durables', '0.7.4');
insert into project (id, name, service_provider_id, code, sector, app_version) values (177, 'Lotlux', 77, 'AGU', 'Basic Industries', '9.94');
insert into project (id, name, service_provider_id, code, sector, app_version) values (178, 'Tampflex', 78, 'CMRE', 'Transportation', '4.12');
insert into project (id, name, service_provider_id, code, sector, app_version) values (179, 'Biodex', 79, 'MBWM', 'Finance', '8.83');
insert into project (id, name, service_provider_id, code, sector, app_version) values (180, 'Wrapsafe', 80, 'GLT', 'Basic Industries', '5.06');
insert into project (id, name, service_provider_id, code, sector, app_version) values (181, 'Prodder', 81, 'FBIZ', 'Finance', '7.11');
insert into project (id, name, service_provider_id, code, sector, app_version) values (182, 'Bigtax', 82, 'PEO', 'n/a', '7.0.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (183, 'Transcof', 83, 'PTC', 'Technology', '0.72');
insert into project (id, name, service_provider_id, code, sector, app_version) values (184, 'Vagram', 84, 'CIM', 'Consumer Services', '8.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (185, 'Voyatouch', 85, 'APTO', 'Health Care', '3.0');
insert into project (id, name, service_provider_id, code, sector, app_version) values (186, 'Prodder', 86, 'EAT', 'Consumer Services', '1.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (187, 'Y-Solowarm', 87, 'LUK', 'Consumer Non-Durables', '6.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (188, 'Tresom', 88, 'SKYW', 'Transportation', '5.76');
insert into project (id, name, service_provider_id, code, sector, app_version) values (189, 'Namfix', 89, 'JBL', 'Technology', '5.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (190, 'Temp', 90, 'DQ', 'Technology', '0.7.7');
insert into project (id, name, service_provider_id, code, sector, app_version) values (191, 'Zathin', 91, 'IPG', 'Technology', '0.8.6');
insert into project (id, name, service_provider_id, code, sector, app_version) values (192, 'Gembucket', 92, 'MACQ', 'n/a', '5.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (193, 'Flowdesk', 93, 'COWN', 'Finance', '4.8');
insert into project (id, name, service_provider_id, code, sector, app_version) values (194, 'Cardify', 94, 'OFG', 'Finance', '4.58');
insert into project (id, name, service_provider_id, code, sector, app_version) values (195, 'Job', 95, 'HE', 'Public Utilities', '1.20');
insert into project (id, name, service_provider_id, code, sector, app_version) values (196, 'Cookley', 96, 'PCRX', 'Health Care', '0.73');
insert into project (id, name, service_provider_id, code, sector, app_version) values (197, 'Span', 97, 'VIIZ', 'Finance', '3.0.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (198, 'Stringtough', 98, 'SXI', 'Technology', '0.1.9');
insert into project (id, name, service_provider_id, code, sector, app_version) values (199, 'Job', 99, 'DGLD', 'Finance', '0.40');
insert into project (id, name, service_provider_id, code, sector, app_version) values (200, 'Alpha', 100, 'MARK', 'Consumer Services', '4.0');
insert into project (id, name, service_provider_id, code, sector, app_version) values (201, 'Veribet', 1, 'QPAC', 'Miscellaneous', '6.7');
insert into project (id, name, service_provider_id, code, sector, app_version) values (202, 'Toughjoyfax', 2, 'CHFC', 'Finance', '7.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (203, 'Flowdesk', 3, 'TELL', 'Energy', '2.6');
insert into project (id, name, service_provider_id, code, sector, app_version) values (204, 'It', 4, 'TTNP', 'Health Care', '6.80');
insert into project (id, name, service_provider_id, code, sector, app_version) values (205, 'Stringtough', 5, 'MORN', 'Finance', '2.31');
insert into project (id, name, service_provider_id, code, sector, app_version) values (206, 'Zoolab', 6, 'FEYE', 'Technology', '2.6.7');
insert into project (id, name, service_provider_id, code, sector, app_version) values (207, 'Home Ing', 7, 'BKT', 'n/a', '8.71');
insert into project (id, name, service_provider_id, code, sector, app_version) values (208, 'Solarbreeze', 8, 'BST', 'n/a', '8.8');
insert into project (id, name, service_provider_id, code, sector, app_version) values (209, 'Treeflex', 9, 'PACD', 'Energy', '1.0.1');
insert into project (id, name, service_provider_id, code, sector, app_version) values (210, 'Span', 10, 'VEAC', 'Finance', '8.61');
insert into project (id, name, service_provider_id, code, sector, app_version) values (211, 'Daltfresh', 11, 'CDC', 'n/a', '2.9.7');
insert into project (id, name, service_provider_id, code, sector, app_version) values (212, 'Cardguard', 12, 'KLXI', 'Capital Goods', '2.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (213, 'Wrapsafe', 13, 'YUMC', 'Consumer Services', '3.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (214, 'Solarbreeze', 14, 'AGI', 'Basic Industries', '0.29');
insert into project (id, name, service_provider_id, code, sector, app_version) values (215, 'Asoka', 15, 'VCO', 'Consumer Non-Durables', '6.0');
insert into project (id, name, service_provider_id, code, sector, app_version) values (216, 'Andalax', 16, 'NVDQ', 'Health Care', '1.9');
insert into project (id, name, service_provider_id, code, sector, app_version) values (217, 'Opela', 17, 'PAGP', 'Energy', '5.78');
insert into project (id, name, service_provider_id, code, sector, app_version) values (218, 'Holdlamis', 18, 'LHO^', 'n/a', '5.00');
insert into project (id, name, service_provider_id, code, sector, app_version) values (219, 'Zamit', 19, 'UVV', 'Consumer Services', '9.2.0');
insert into project (id, name, service_provider_id, code, sector, app_version) values (220, 'Daltfresh', 20, 'TITN', 'Consumer Services', '0.13');
insert into project (id, name, service_provider_id, code, sector, app_version) values (221, 'Transcof', 21, 'CNCE', 'Health Care', '6.0');
insert into project (id, name, service_provider_id, code, sector, app_version) values (222, 'Bamity', 22, 'MPW', 'Consumer Services', '1.0.9');
insert into project (id, name, service_provider_id, code, sector, app_version) values (223, 'Bitchip', 23, 'LORL', 'Technology', '0.4.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (224, 'Zamit', 24, 'CBB', 'Public Utilities', '4.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (225, 'Zamit', 25, 'NRT', 'Energy', '6.59');
insert into project (id, name, service_provider_id, code, sector, app_version) values (226, 'Voltsillam', 26, 'CCIH', 'Technology', '0.4.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (227, 'Voltsillam', 27, 'REX', 'Basic Industries', '4.1');
insert into project (id, name, service_provider_id, code, sector, app_version) values (228, 'Otcom', 28, 'KBWR', 'n/a', '5.8');
insert into project (id, name, service_provider_id, code, sector, app_version) values (229, 'Stronghold', 29, 'PCI', 'n/a', '4.2.0');
insert into project (id, name, service_provider_id, code, sector, app_version) values (230, 'Voltsillam', 30, 'KB', 'Finance', '6.6.0');
insert into project (id, name, service_provider_id, code, sector, app_version) values (231, 'Keylex', 31, 'MDR', 'Capital Goods', '4.32');
insert into project (id, name, service_provider_id, code, sector, app_version) values (232, 'Gembucket', 32, 'BAC^', 'Finance', '0.4.0');
insert into project (id, name, service_provider_id, code, sector, app_version) values (233, 'Duobam', 33, 'CRIS', 'Health Care', '3.1.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (234, 'Andalax', 34, 'TLT', 'n/a', '0.50');
insert into project (id, name, service_provider_id, code, sector, app_version) values (235, 'Sonsing', 35, 'LWAY', 'Consumer Non-Durables', '1.65');
insert into project (id, name, service_provider_id, code, sector, app_version) values (236, 'Cookley', 36, 'COBZ', 'Finance', '5.64');
insert into project (id, name, service_provider_id, code, sector, app_version) values (237, 'Bitwolf', 37, 'AHT^', 'n/a', '0.9.7');
insert into project (id, name, service_provider_id, code, sector, app_version) values (238, 'Hatity', 38, 'PLUG', 'Energy', '3.1');
insert into project (id, name, service_provider_id, code, sector, app_version) values (239, 'Cookley', 39, 'HIE', 'n/a', '2.4.6');
insert into project (id, name, service_provider_id, code, sector, app_version) values (240, 'Holdlamis', 40, 'AAT', 'Consumer Services', '0.1.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (241, 'Duobam', 41, 'MAMS', 'Technology', '0.81');
insert into project (id, name, service_provider_id, code, sector, app_version) values (242, 'Aerified', 42, 'AXGN', 'Health Care', '1.8');
insert into project (id, name, service_provider_id, code, sector, app_version) values (243, 'Alphazap', 43, 'CUDA', 'Technology', '9.7');
insert into project (id, name, service_provider_id, code, sector, app_version) values (244, 'Quo Lux', 44, 'RDWR', 'Miscellaneous', '2.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (245, 'Mat Lam Tam', 45, 'MICT', 'Capital Goods', '8.77');
insert into project (id, name, service_provider_id, code, sector, app_version) values (246, 'Opela', 46, 'PEBO', 'Finance', '8.8');
insert into project (id, name, service_provider_id, code, sector, app_version) values (247, 'Namfix', 47, 'GBDC', 'n/a', '0.3.4');
insert into project (id, name, service_provider_id, code, sector, app_version) values (248, 'Bytecard', 48, 'STRT', 'Capital Goods', '0.2.0');
insert into project (id, name, service_provider_id, code, sector, app_version) values (249, 'Zoolab', 49, 'MNK', 'Health Care', '1.0.9');
insert into project (id, name, service_provider_id, code, sector, app_version) values (250, 'Holdlamis', 50, 'CYAN', 'Consumer Durables', '0.57');
insert into project (id, name, service_provider_id, code, sector, app_version) values (251, 'Otcom', 51, 'RELV', 'Health Care', '0.77');
insert into project (id, name, service_provider_id, code, sector, app_version) values (252, 'Stronghold', 52, 'CAH', 'Health Care', '0.36');
insert into project (id, name, service_provider_id, code, sector, app_version) values (253, 'Fintone', 53, 'KAP', 'n/a', '9.6.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (254, 'Rank', 54, 'ATTO', 'Public Utilities', '0.7.9');
insert into project (id, name, service_provider_id, code, sector, app_version) values (255, 'Viva', 55, 'BYD', 'Consumer Services', '3.43');
insert into project (id, name, service_provider_id, code, sector, app_version) values (256, 'Bytecard', 56, 'NSM', 'Finance', '0.3.9');
insert into project (id, name, service_provider_id, code, sector, app_version) values (257, 'Stringtough', 57, 'BVN', 'Basic Industries', '7.5.1');
insert into project (id, name, service_provider_id, code, sector, app_version) values (258, 'Gembucket', 58, 'ALL^', 'n/a', '6.6');
insert into project (id, name, service_provider_id, code, sector, app_version) values (259, 'Sonair', 59, 'ABIL', 'Finance', '6.92');
insert into project (id, name, service_provider_id, code, sector, app_version) values (260, 'Stringtough', 60, 'FCFS', 'Consumer Services', '0.1.9');
insert into project (id, name, service_provider_id, code, sector, app_version) values (261, 'Zoolab', 61, 'PSDV', 'Capital Goods', '3.6.5');
insert into project (id, name, service_provider_id, code, sector, app_version) values (262, 'Regrant', 62, 'CORT', 'Health Care', '3.2.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (263, 'Zaam-Dox', 63, 'PEI^', 'n/a', '0.8.9');
insert into project (id, name, service_provider_id, code, sector, app_version) values (264, 'Y-find', 64, 'EMIF', 'n/a', '2.7.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (265, 'Zoolab', 65, 'TPGE', 'n/a', '2.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (266, 'Tempsoft', 66, 'MMAC', 'Finance', '9.8.4');
insert into project (id, name, service_provider_id, code, sector, app_version) values (267, 'Span', 67, 'OSBC', 'Finance', '0.34');
insert into project (id, name, service_provider_id, code, sector, app_version) values (268, 'Keylex', 68, 'BREW', 'Consumer Non-Durables', '0.9.6');
insert into project (id, name, service_provider_id, code, sector, app_version) values (269, 'It', 69, 'AIW', 'Finance', '8.5');
insert into project (id, name, service_provider_id, code, sector, app_version) values (270, 'Alphazap', 70, 'BDX', 'Health Care', '8.1');
insert into project (id, name, service_provider_id, code, sector, app_version) values (271, 'Fintone', 71, 'MPWR', 'Technology', '7.19');
insert into project (id, name, service_provider_id, code, sector, app_version) values (272, 'Konklab', 72, 'BEL', 'Consumer Services', '7.79');
insert into project (id, name, service_provider_id, code, sector, app_version) values (273, 'Ventosanzap', 73, 'SAL', 'Finance', '0.3.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (274, 'Y-Solowarm', 74, 'PERF', 'Consumer Services', '1.98');
insert into project (id, name, service_provider_id, code, sector, app_version) values (275, 'Cookley', 75, 'ANCB', 'Finance', '8.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (276, 'Lotstring', 76, 'KBWD', 'n/a', '6.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (277, 'Quo Lux', 77, 'WFC^', 'n/a', '0.24');
insert into project (id, name, service_provider_id, code, sector, app_version) values (278, 'It', 78, 'EEQ', 'Energy', '0.3.6');
insert into project (id, name, service_provider_id, code, sector, app_version) values (279, 'Lotstring', 79, 'SASR', 'Finance', '0.49');
insert into project (id, name, service_provider_id, code, sector, app_version) values (280, 'Stim', 80, 'HCLP', 'Basic Industries', '0.76');
insert into project (id, name, service_provider_id, code, sector, app_version) values (281, 'Fixflex', 81, 'PCI', 'n/a', '0.41');
insert into project (id, name, service_provider_id, code, sector, app_version) values (282, 'Voltsillam', 82, 'GGP', 'Consumer Services', '6.4');
insert into project (id, name, service_provider_id, code, sector, app_version) values (283, 'Daltfresh', 83, 'SHAK', 'Consumer Services', '1.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (284, 'Mat Lam Tam', 84, 'IIPR', 'Finance', '0.4.7');
insert into project (id, name, service_provider_id, code, sector, app_version) values (285, 'Solarbreeze', 85, 'TICC', 'n/a', '6.88');
insert into project (id, name, service_provider_id, code, sector, app_version) values (286, 'Sonair', 86, 'PGEM', 'Basic Industries', '0.42');
insert into project (id, name, service_provider_id, code, sector, app_version) values (287, 'Treeflex', 87, 'CTBI', 'Finance', '8.7.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (288, 'Zathin', 88, 'NCOM', 'Finance', '0.4.5');
insert into project (id, name, service_provider_id, code, sector, app_version) values (289, 'Bytecard', 89, 'RFTA', 'Consumer Services', '3.8');
insert into project (id, name, service_provider_id, code, sector, app_version) values (290, 'Cookley', 90, 'ETM', 'Consumer Services', '0.28');
insert into project (id, name, service_provider_id, code, sector, app_version) values (291, 'Prodder', 91, 'IDXX', 'Health Care', '0.1.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (292, 'Hatity', 92, 'GIFI', 'Capital Goods', '0.55');
insert into project (id, name, service_provider_id, code, sector, app_version) values (293, 'Tresom', 93, 'PFMT', 'Consumer Services', '4.0');
insert into project (id, name, service_provider_id, code, sector, app_version) values (294, 'Asoka', 94, 'MLR', 'Capital Goods', '0.48');
insert into project (id, name, service_provider_id, code, sector, app_version) values (295, 'Voyatouch', 95, 'DCM', 'Technology', '0.36');
insert into project (id, name, service_provider_id, code, sector, app_version) values (296, 'Bitwolf', 96, 'WB', 'Technology', '0.9.6');
insert into project (id, name, service_provider_id, code, sector, app_version) values (297, 'Subin', 97, 'HSTM', 'Technology', '0.63');
insert into project (id, name, service_provider_id, code, sector, app_version) values (298, 'Alpha', 98, 'YUM', 'Consumer Services', '9.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (299, 'Cookley', 99, 'IAE', 'n/a', '9.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (300, 'It', 100, 'NS^B', 'n/a', '0.3.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (301, 'Opela', 1, 'JAX', 'Consumer Services', '1.8');
insert into project (id, name, service_provider_id, code, sector, app_version) values (302, 'Stringtough', 2, 'ISG', 'Finance', '0.73');
insert into project (id, name, service_provider_id, code, sector, app_version) values (303, 'Stronghold', 3, 'SRF', 'n/a', '3.7.5');
insert into project (id, name, service_provider_id, code, sector, app_version) values (304, 'Stim', 4, 'ARR', 'Consumer Services', '0.4.8');
insert into project (id, name, service_provider_id, code, sector, app_version) values (305, 'Treeflex', 5, 'EAGL', 'Finance', '6.42');
insert into project (id, name, service_provider_id, code, sector, app_version) values (306, 'Stronghold', 6, 'JFR', 'n/a', '3.7');
insert into project (id, name, service_provider_id, code, sector, app_version) values (307, 'Y-find', 7, 'GSOL', 'Consumer Services', '5.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (308, 'Namfix', 8, 'WKHS', 'Capital Goods', '5.11');
insert into project (id, name, service_provider_id, code, sector, app_version) values (309, 'Tin', 9, 'DYNC', 'Public Utilities', '0.4.5');
insert into project (id, name, service_provider_id, code, sector, app_version) values (310, 'Keylex', 10, 'AEGN', 'Basic Industries', '9.6');
insert into project (id, name, service_provider_id, code, sector, app_version) values (311, 'Fix San', 11, 'PSCT', 'n/a', '0.32');
insert into project (id, name, service_provider_id, code, sector, app_version) values (312, 'Mat Lam Tam', 12, 'TTD', 'Technology', '4.9.9');
insert into project (id, name, service_provider_id, code, sector, app_version) values (313, 'Treeflex', 13, 'TSEM', 'Technology', '9.8.6');
insert into project (id, name, service_provider_id, code, sector, app_version) values (314, 'It', 14, 'MSG', 'Consumer Services', '0.47');
insert into project (id, name, service_provider_id, code, sector, app_version) values (315, 'Y-Solowarm', 15, 'ABY', 'Public Utilities', '1.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (316, 'Aerified', 16, 'FLGT', 'Health Care', '5.7.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (317, 'Transcof', 17, 'WATT', 'Technology', '4.2.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (318, 'Sub-Ex', 18, 'TNP^', 'n/a', '1.76');
insert into project (id, name, service_provider_id, code, sector, app_version) values (319, 'Domainer', 19, 'QRHC', 'Technology', '6.7');
insert into project (id, name, service_provider_id, code, sector, app_version) values (320, 'Konklab', 20, 'DTUS', 'Finance', '0.7.8');
insert into project (id, name, service_provider_id, code, sector, app_version) values (321, 'Fix San', 21, 'CRTO', 'Technology', '3.33');
insert into project (id, name, service_provider_id, code, sector, app_version) values (322, 'Lotstring', 22, 'BAC', 'Finance', '0.4.1');
insert into project (id, name, service_provider_id, code, sector, app_version) values (323, 'Alphazap', 23, 'JE', 'Public Utilities', '0.9.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (324, 'It', 24, 'HDS', 'Consumer Services', '1.1.1');
insert into project (id, name, service_provider_id, code, sector, app_version) values (325, 'Tresom', 25, 'MDLZ', 'Consumer Non-Durables', '0.61');
insert into project (id, name, service_provider_id, code, sector, app_version) values (326, 'Fix San', 26, 'BSX', 'Health Care', '5.2.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (327, 'Konklab', 27, 'SQZZ', 'n/a', '7.29');
insert into project (id, name, service_provider_id, code, sector, app_version) values (328, 'It', 28, 'JE', 'Public Utilities', '2.8');
insert into project (id, name, service_provider_id, code, sector, app_version) values (329, 'Prodder', 29, 'IPWR', 'Energy', '7.6.9');
insert into project (id, name, service_provider_id, code, sector, app_version) values (330, 'Redhold', 30, 'OVID', 'Health Care', '0.8.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (331, 'Sonair', 31, 'PEBO', 'Finance', '3.4');
insert into project (id, name, service_provider_id, code, sector, app_version) values (332, 'Matsoft', 32, 'REX', 'Basic Industries', '9.0.1');
insert into project (id, name, service_provider_id, code, sector, app_version) values (333, 'Pannier', 33, 'PRSC', 'Consumer Services', '4.9.5');
insert into project (id, name, service_provider_id, code, sector, app_version) values (334, 'Domainer', 34, 'TPX', 'Consumer Durables', '7.9.7');
insert into project (id, name, service_provider_id, code, sector, app_version) values (335, 'Namfix', 35, 'TITN', 'Consumer Services', '8.4');
insert into project (id, name, service_provider_id, code, sector, app_version) values (336, 'Ronstring', 36, 'ARR^', 'n/a', '1.71');
insert into project (id, name, service_provider_id, code, sector, app_version) values (337, 'Veribet', 37, 'SPNE', 'Health Care', '1.6');
insert into project (id, name, service_provider_id, code, sector, app_version) values (338, 'Lotlux', 38, 'ACFC', 'Finance', '6.3.7');
insert into project (id, name, service_provider_id, code, sector, app_version) values (339, 'Prodder', 39, 'STT^', 'n/a', '3.15');
insert into project (id, name, service_provider_id, code, sector, app_version) values (340, 'Rank', 40, 'FSAM', 'Finance', '0.57');
insert into project (id, name, service_provider_id, code, sector, app_version) values (341, 'Tampflex', 41, 'CNC', 'Health Care', '0.5.8');
insert into project (id, name, service_provider_id, code, sector, app_version) values (342, 'Wrapsafe', 42, 'TUES', 'Consumer Services', '7.10');
insert into project (id, name, service_provider_id, code, sector, app_version) values (343, 'Gembucket', 43, 'WPZ', 'Public Utilities', '2.36');
insert into project (id, name, service_provider_id, code, sector, app_version) values (344, 'Tampflex', 44, 'CADE', 'Finance', '9.8');
insert into project (id, name, service_provider_id, code, sector, app_version) values (345, 'Fixflex', 45, 'RPRX', 'Health Care', '6.60');
insert into project (id, name, service_provider_id, code, sector, app_version) values (346, 'Zaam-Dox', 46, 'PM', 'Consumer Non-Durables', '5.0');
insert into project (id, name, service_provider_id, code, sector, app_version) values (347, 'Stim', 47, 'TNP', 'Transportation', '9.0');
insert into project (id, name, service_provider_id, code, sector, app_version) values (348, 'Tin', 48, 'TLRD', 'Consumer Services', '0.8.9');
insert into project (id, name, service_provider_id, code, sector, app_version) values (349, 'Alpha', 49, 'COBZ', 'Finance', '6.7');
insert into project (id, name, service_provider_id, code, sector, app_version) values (350, 'Viva', 50, 'TTF', 'n/a', '0.4.1');
insert into project (id, name, service_provider_id, code, sector, app_version) values (351, 'Cardguard', 51, 'PPR', 'n/a', '0.98');
insert into project (id, name, service_provider_id, code, sector, app_version) values (352, 'Solarbreeze', 52, 'TNH', 'Basic Industries', '7.11');
insert into project (id, name, service_provider_id, code, sector, app_version) values (353, 'Zoolab', 53, 'AVB', 'Consumer Services', '0.17');
insert into project (id, name, service_provider_id, code, sector, app_version) values (354, 'Overhold', 54, 'RRR', 'Consumer Services', '1.3.8');
insert into project (id, name, service_provider_id, code, sector, app_version) values (355, 'Mat Lam Tam', 55, 'SOI', 'Energy', '0.8.1');
insert into project (id, name, service_provider_id, code, sector, app_version) values (356, 'Viva', 56, 'IP', 'Basic Industries', '5.35');
insert into project (id, name, service_provider_id, code, sector, app_version) values (357, 'Duobam', 57, 'STB', 'Transportation', '5.2.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (358, 'Latlux', 58, 'ACWI', 'n/a', '0.80');
insert into project (id, name, service_provider_id, code, sector, app_version) values (359, 'Lotlux', 59, 'VIAB', 'Consumer Services', '5.6');
insert into project (id, name, service_provider_id, code, sector, app_version) values (360, 'Opela', 60, 'JPI', 'n/a', '1.2.4');
insert into project (id, name, service_provider_id, code, sector, app_version) values (361, 'Span', 61, 'DRAM', 'Technology', '5.80');
insert into project (id, name, service_provider_id, code, sector, app_version) values (362, 'Prodder', 62, 'PSA^', 'n/a', '0.1.7');
insert into project (id, name, service_provider_id, code, sector, app_version) values (363, 'Alpha', 63, 'WSBC', 'Finance', '0.76');
insert into project (id, name, service_provider_id, code, sector, app_version) values (364, 'Viva', 64, 'FENX', 'Consumer Services', '0.4.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (365, 'Lotstring', 65, 'LSXM', 'Consumer Services', '0.4.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (366, 'Span', 66, 'AMT', 'Consumer Services', '0.5.8');
insert into project (id, name, service_provider_id, code, sector, app_version) values (367, 'Bitwolf', 67, 'FCX', 'Basic Industries', '3.94');
insert into project (id, name, service_provider_id, code, sector, app_version) values (368, 'Y-Solowarm', 68, 'RWLK', 'Health Care', '1.59');
insert into project (id, name, service_provider_id, code, sector, app_version) values (369, 'Hatity', 69, 'ATTU', 'Technology', '2.4');
insert into project (id, name, service_provider_id, code, sector, app_version) values (370, 'Tin', 70, 'QUMU', 'Technology', '1.6.5');
insert into project (id, name, service_provider_id, code, sector, app_version) values (371, 'Zoolab', 71, 'PBA', 'Energy', '7.77');
insert into project (id, name, service_provider_id, code, sector, app_version) values (372, 'Greenlam', 72, 'UVV', 'Consumer Services', '0.4.8');
insert into project (id, name, service_provider_id, code, sector, app_version) values (373, 'Alphazap', 73, 'MGEE', 'Energy', '0.33');
insert into project (id, name, service_provider_id, code, sector, app_version) values (374, 'Domainer', 74, 'HY', 'Capital Goods', '0.9.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (375, 'Viva', 75, 'FELE', 'Consumer Durables', '6.6');
insert into project (id, name, service_provider_id, code, sector, app_version) values (376, 'Domainer', 76, 'HUBS', 'Technology', '0.5.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (377, 'Sonair', 77, 'PCSB', 'Finance', '8.05');
insert into project (id, name, service_provider_id, code, sector, app_version) values (378, 'Keylex', 78, 'FDT', 'n/a', '7.39');
insert into project (id, name, service_provider_id, code, sector, app_version) values (379, 'Alphazap', 79, 'JSD', 'n/a', '2.56');
insert into project (id, name, service_provider_id, code, sector, app_version) values (380, 'Sonsing', 80, 'MBOT', 'Health Care', '2.89');
insert into project (id, name, service_provider_id, code, sector, app_version) values (381, 'Namfix', 81, 'VALX', 'n/a', '0.17');
insert into project (id, name, service_provider_id, code, sector, app_version) values (382, 'Stringtough', 82, 'ACET', 'Health Care', '0.47');
insert into project (id, name, service_provider_id, code, sector, app_version) values (383, 'Biodex', 83, 'STK', 'n/a', '0.2.8');
insert into project (id, name, service_provider_id, code, sector, app_version) values (384, 'Zathin', 84, 'BDGE', 'Finance', '1.4');
insert into project (id, name, service_provider_id, code, sector, app_version) values (385, 'Zontrax', 85, 'SAN^', 'n/a', '0.39');
insert into project (id, name, service_provider_id, code, sector, app_version) values (386, 'Trippledex', 86, 'PHI', 'Public Utilities', '0.3.6');
insert into project (id, name, service_provider_id, code, sector, app_version) values (387, 'Cookley', 87, 'AVIR', 'Health Care', '0.61');
insert into project (id, name, service_provider_id, code, sector, app_version) values (388, 'Fix San', 88, 'FCF', 'Finance', '9.9');
insert into project (id, name, service_provider_id, code, sector, app_version) values (389, 'Aerified', 89, 'SQNS', 'Technology', '8.85');
insert into project (id, name, service_provider_id, code, sector, app_version) values (390, 'Konklux', 90, 'FLT', 'Miscellaneous', '8.8');
insert into project (id, name, service_provider_id, code, sector, app_version) values (391, 'Fix San', 91, 'FNY', 'n/a', '2.47');
insert into project (id, name, service_provider_id, code, sector, app_version) values (392, 'Latlux', 92, 'TISA', 'Technology', '3.13');
insert into project (id, name, service_provider_id, code, sector, app_version) values (393, 'Sub-Ex', 93, 'PHM', 'Capital Goods', '2.4.0');
insert into project (id, name, service_provider_id, code, sector, app_version) values (394, 'Tampflex', 94, 'AIW', 'Finance', '0.5.0');
insert into project (id, name, service_provider_id, code, sector, app_version) values (395, 'Zathin', 95, 'AED', 'Finance', '8.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (396, 'Konklab', 96, 'NAII', 'Consumer Durables', '0.28');
insert into project (id, name, service_provider_id, code, sector, app_version) values (397, 'Subin', 97, 'INTC', 'Technology', '8.0.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (398, 'Tres-Zap', 98, 'TPX', 'Consumer Durables', '5.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (399, 'Flexidy', 99, 'EVA', 'Basic Industries', '4.9');
insert into project (id, name, service_provider_id, code, sector, app_version) values (400, 'Transcof', 100, 'AVIR', 'Health Care', '3.36');
insert into project (id, name, service_provider_id, code, sector, app_version) values (401, 'Opela', 1, 'LQDT', 'Miscellaneous', '0.7.7');
insert into project (id, name, service_provider_id, code, sector, app_version) values (402, 'Bigtax', 2, 'GPAC', 'Health Care', '9.1');
insert into project (id, name, service_provider_id, code, sector, app_version) values (403, 'Stringtough', 3, 'AMBA', 'Technology', '1.75');
insert into project (id, name, service_provider_id, code, sector, app_version) values (404, 'Matsoft', 4, 'BIDU', 'Technology', '9.89');
insert into project (id, name, service_provider_id, code, sector, app_version) values (405, 'Zamit', 5, 'KOSS', 'Consumer Non-Durables', '2.4');
insert into project (id, name, service_provider_id, code, sector, app_version) values (406, 'Home Ing', 6, 'ARCH', 'Energy', '5.6');
insert into project (id, name, service_provider_id, code, sector, app_version) values (407, 'Bigtax', 7, 'SSRI', 'Basic Industries', '7.4');
insert into project (id, name, service_provider_id, code, sector, app_version) values (408, 'Asoka', 8, 'GRX^', 'n/a', '0.61');
insert into project (id, name, service_provider_id, code, sector, app_version) values (409, 'Zathin', 9, 'CLUB', 'Consumer Services', '5.5.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (410, 'Greenlam', 10, 'GFI', 'Basic Industries', '9.1.6');
insert into project (id, name, service_provider_id, code, sector, app_version) values (411, 'Regrant', 11, 'SUMR', 'Consumer Durables', '0.76');
insert into project (id, name, service_provider_id, code, sector, app_version) values (412, 'Gembucket', 12, 'NDRO', 'Energy', '4.6');
insert into project (id, name, service_provider_id, code, sector, app_version) values (413, 'Vagram', 13, 'MT', 'Basic Industries', '0.1.7');
insert into project (id, name, service_provider_id, code, sector, app_version) values (414, 'Fintone', 14, 'HQCL', 'Technology', '1.54');
insert into project (id, name, service_provider_id, code, sector, app_version) values (415, 'Zathin', 15, 'ABCD', 'Consumer Services', '0.16');
insert into project (id, name, service_provider_id, code, sector, app_version) values (416, 'Bigtax', 16, 'HBM', 'Basic Industries', '6.1.8');
insert into project (id, name, service_provider_id, code, sector, app_version) values (417, 'Flexidy', 17, 'RVLT', 'Consumer Durables', '7.30');
insert into project (id, name, service_provider_id, code, sector, app_version) values (418, 'Latlux', 18, 'NMY', 'n/a', '0.3.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (419, 'Tres-Zap', 19, 'NBD', 'n/a', '0.5.8');
insert into project (id, name, service_provider_id, code, sector, app_version) values (420, 'Stim', 20, 'HOG', 'Consumer Non-Durables', '1.08');
insert into project (id, name, service_provider_id, code, sector, app_version) values (421, 'Tin', 21, 'VEAC', 'Finance', '0.87');
insert into project (id, name, service_provider_id, code, sector, app_version) values (422, 'Rank', 22, 'FNY', 'n/a', '9.0');
insert into project (id, name, service_provider_id, code, sector, app_version) values (423, 'Tin', 23, 'ORA', 'Public Utilities', '7.77');
insert into project (id, name, service_provider_id, code, sector, app_version) values (424, 'Kanlam', 24, 'PUB', 'Finance', '2.9.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (425, 'Fixflex', 25, 'VEC', 'Consumer Services', '0.86');
insert into project (id, name, service_provider_id, code, sector, app_version) values (426, 'Gembucket', 26, 'VICL', 'Health Care', '0.6.4');
insert into project (id, name, service_provider_id, code, sector, app_version) values (427, 'Cardify', 27, 'PNC', 'Finance', '0.1.4');
insert into project (id, name, service_provider_id, code, sector, app_version) values (428, 'It', 28, 'NIM', 'n/a', '6.5.6');
insert into project (id, name, service_provider_id, code, sector, app_version) values (429, 'Y-Solowarm', 29, 'VIAB', 'Consumer Services', '0.37');
insert into project (id, name, service_provider_id, code, sector, app_version) values (430, 'Zoolab', 30, 'HBCP', 'Finance', '8.5');
insert into project (id, name, service_provider_id, code, sector, app_version) values (431, 'Tempsoft', 31, 'JCTC', 'Consumer Services', '6.70');
insert into project (id, name, service_provider_id, code, sector, app_version) values (432, 'Asoka', 32, 'HL^B', 'Basic Industries', '7.1.4');
insert into project (id, name, service_provider_id, code, sector, app_version) values (433, 'Konklab', 33, 'MIRN', 'Health Care', '6.48');
insert into project (id, name, service_provider_id, code, sector, app_version) values (434, 'Fixflex', 34, 'ELGX', 'Health Care', '0.2.1');
insert into project (id, name, service_provider_id, code, sector, app_version) values (435, 'Flexidy', 35, 'AEP', 'Public Utilities', '7.4.7');
insert into project (id, name, service_provider_id, code, sector, app_version) values (436, 'Alphazap', 36, 'VONE', 'n/a', '0.4.1');
insert into project (id, name, service_provider_id, code, sector, app_version) values (437, 'Transcof', 37, 'WTTR', 'Energy', '2.0');
insert into project (id, name, service_provider_id, code, sector, app_version) values (438, 'Bamity', 38, 'OCN', 'Finance', '2.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (439, 'Bitchip', 39, 'MAMS', 'Technology', '0.95');
insert into project (id, name, service_provider_id, code, sector, app_version) values (440, 'Hatity', 40, 'GPK', 'Consumer Durables', '5.7');
insert into project (id, name, service_provider_id, code, sector, app_version) values (441, 'Fixflex', 41, 'CHMI', 'Consumer Services', '5.29');
insert into project (id, name, service_provider_id, code, sector, app_version) values (442, 'Tin', 42, 'LYV', 'Consumer Services', '8.8.4');
insert into project (id, name, service_provider_id, code, sector, app_version) values (443, 'Fintone', 43, 'NVMI', 'Capital Goods', '0.8.6');
insert into project (id, name, service_provider_id, code, sector, app_version) values (444, 'Sonair', 44, 'CHCT', 'Consumer Services', '3.4');
insert into project (id, name, service_provider_id, code, sector, app_version) values (445, 'Mat Lam Tam', 45, 'CIF', 'n/a', '2.6.8');
insert into project (id, name, service_provider_id, code, sector, app_version) values (446, 'Quo Lux', 46, 'WTS', 'Capital Goods', '4.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (447, 'Ronstring', 47, 'QUAD', 'Miscellaneous', '0.33');
insert into project (id, name, service_provider_id, code, sector, app_version) values (448, 'Zontrax', 48, 'PSET', 'n/a', '8.4.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (449, 'Job', 49, 'JMEI', 'Consumer Services', '5.65');
insert into project (id, name, service_provider_id, code, sector, app_version) values (450, 'Sonair', 50, 'QADA', 'Technology', '2.0.9');
insert into project (id, name, service_provider_id, code, sector, app_version) values (451, 'Vagram', 51, 'KE', 'Technology', '2.9.9');
insert into project (id, name, service_provider_id, code, sector, app_version) values (452, 'Zaam-Dox', 52, 'PNTR', 'Technology', '3.5.6');
insert into project (id, name, service_provider_id, code, sector, app_version) values (453, 'Wrapsafe', 53, 'IRMD', 'Health Care', '6.54');
insert into project (id, name, service_provider_id, code, sector, app_version) values (454, 'Otcom', 54, 'INFI', 'Health Care', '7.4.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (455, 'Domainer', 55, 'DHXM', 'n/a', '1.1');
insert into project (id, name, service_provider_id, code, sector, app_version) values (456, 'Asoka', 56, 'L', 'Finance', '0.4.1');
insert into project (id, name, service_provider_id, code, sector, app_version) values (457, 'Trippledex', 57, 'PKG', 'Consumer Durables', '4.51');
insert into project (id, name, service_provider_id, code, sector, app_version) values (458, 'Redhold', 58, 'PFSI', 'Finance', '8.3.0');
insert into project (id, name, service_provider_id, code, sector, app_version) values (459, 'Aerified', 59, 'FWP', 'Health Care', '3.0.4');
insert into project (id, name, service_provider_id, code, sector, app_version) values (460, 'Viva', 60, 'MTB', 'Finance', '0.71');
insert into project (id, name, service_provider_id, code, sector, app_version) values (461, 'Subin', 61, 'ALG', 'Capital Goods', '0.73');
insert into project (id, name, service_provider_id, code, sector, app_version) values (462, 'Lotlux', 62, 'BIOL', 'Health Care', '4.86');
insert into project (id, name, service_provider_id, code, sector, app_version) values (463, 'Y-Solowarm', 63, 'CTBB', 'Public Utilities', '5.1.9');
insert into project (id, name, service_provider_id, code, sector, app_version) values (464, 'Fix San', 64, 'CBAN', 'Finance', '0.5.6');
insert into project (id, name, service_provider_id, code, sector, app_version) values (465, 'Latlux', 65, 'PSB^', 'n/a', '0.91');
insert into project (id, name, service_provider_id, code, sector, app_version) values (466, 'Stim', 66, 'SGYP', 'Health Care', '8.87');
insert into project (id, name, service_provider_id, code, sector, app_version) values (467, 'Asoka', 67, 'ARE', 'Consumer Services', '0.62');
insert into project (id, name, service_provider_id, code, sector, app_version) values (468, 'Voltsillam', 68, 'USB^', 'n/a', '0.8.0');
insert into project (id, name, service_provider_id, code, sector, app_version) values (469, 'Fixflex', 69, 'NDRA', 'n/a', '9.7');
insert into project (id, name, service_provider_id, code, sector, app_version) values (470, 'Alpha', 70, 'FCFS', 'Consumer Services', '3.5');
insert into project (id, name, service_provider_id, code, sector, app_version) values (471, 'Konklab', 71, 'ZBRA', 'Technology', '0.2.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (472, 'Zoolab', 72, 'ASML', 'Technology', '0.49');
insert into project (id, name, service_provider_id, code, sector, app_version) values (473, 'Kanlam', 73, 'OTIV', 'Technology', '3.9');
insert into project (id, name, service_provider_id, code, sector, app_version) values (474, 'Flexidy', 74, 'GBAB', 'n/a', '7.7');
insert into project (id, name, service_provider_id, code, sector, app_version) values (475, 'Domainer', 75, 'ALLE', 'Consumer Services', '4.4');
insert into project (id, name, service_provider_id, code, sector, app_version) values (476, 'Holdlamis', 76, 'GECC', 'n/a', '7.99');
insert into project (id, name, service_provider_id, code, sector, app_version) values (477, 'Lotstring', 77, 'CSX', 'Transportation', '7.75');
insert into project (id, name, service_provider_id, code, sector, app_version) values (478, 'Sub-Ex', 78, 'UONE', 'Consumer Services', '6.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (479, 'Job', 79, 'HL', 'Basic Industries', '0.26');
insert into project (id, name, service_provider_id, code, sector, app_version) values (480, 'Regrant', 80, 'CYRX', 'Transportation', '5.60');
insert into project (id, name, service_provider_id, code, sector, app_version) values (481, 'It', 81, 'AINV', 'n/a', '1.6');
insert into project (id, name, service_provider_id, code, sector, app_version) values (482, 'Redhold', 82, 'CETV', 'Consumer Services', '0.9.1');
insert into project (id, name, service_provider_id, code, sector, app_version) values (483, 'Toughjoyfax', 83, 'OPHT', 'Health Care', '0.88');
insert into project (id, name, service_provider_id, code, sector, app_version) values (484, 'Cardify', 84, 'AFH', 'Finance', '1.0');
insert into project (id, name, service_provider_id, code, sector, app_version) values (485, 'Opela', 85, 'PYDS', 'Finance', '6.1');
insert into project (id, name, service_provider_id, code, sector, app_version) values (486, 'Veribet', 86, 'SHO^', 'n/a', '1.86');
insert into project (id, name, service_provider_id, code, sector, app_version) values (487, 'Keylex', 87, 'ALJ', 'Energy', '3.8');
insert into project (id, name, service_provider_id, code, sector, app_version) values (488, 'Aerified', 88, 'ECOL', 'Public Utilities', '0.69');
insert into project (id, name, service_provider_id, code, sector, app_version) values (489, 'Duobam', 89, 'GF', 'n/a', '8.8.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (490, 'Veribet', 90, 'NTGR', 'Public Utilities', '0.46');
insert into project (id, name, service_provider_id, code, sector, app_version) values (491, 'Job', 91, 'DNOW', 'Energy', '0.81');
insert into project (id, name, service_provider_id, code, sector, app_version) values (492, 'Greenlam', 92, 'PSA^', 'Consumer Services', '8.5');
insert into project (id, name, service_provider_id, code, sector, app_version) values (493, 'Tres-Zap', 93, 'TDJ', 'Public Utilities', '0.73');
insert into project (id, name, service_provider_id, code, sector, app_version) values (494, 'Zontrax', 94, 'GRPN', 'Technology', '0.48');
insert into project (id, name, service_provider_id, code, sector, app_version) values (495, 'It', 95, 'BVXV', 'Health Care', '8.17');
insert into project (id, name, service_provider_id, code, sector, app_version) values (496, 'Zontrax', 96, 'BGR', 'n/a', '0.92');
insert into project (id, name, service_provider_id, code, sector, app_version) values (497, 'Home Ing', 97, 'FGL', 'Finance', '1.3.8');
insert into project (id, name, service_provider_id, code, sector, app_version) values (498, 'Toughjoyfax', 98, 'SEMG', 'Energy', '6.07');
insert into project (id, name, service_provider_id, code, sector, app_version) values (499, 'Keylex', 99, 'HBCP', 'Finance', '0.78');
insert into project (id, name, service_provider_id, code, sector, app_version) values (500, 'Viva', 100, 'WGO', 'Consumer Non-Durables', '5.8');
insert into project (id, name, service_provider_id, code, sector, app_version) values (501, 'Bytecard', 1, 'INFN', 'Public Utilities', '1.8.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (502, 'Keylex', 2, 'OFG', 'Finance', '0.14');
insert into project (id, name, service_provider_id, code, sector, app_version) values (503, 'Konklab', 3, 'NVGS', 'Transportation', '0.31');
insert into project (id, name, service_provider_id, code, sector, app_version) values (504, 'Tin', 4, 'ESPR', 'Health Care', '2.7.4');
insert into project (id, name, service_provider_id, code, sector, app_version) values (505, 'Tampflex', 5, 'EW', 'Health Care', '1.97');
insert into project (id, name, service_provider_id, code, sector, app_version) values (506, 'Namfix', 6, 'LGCY', 'Energy', '4.63');
insert into project (id, name, service_provider_id, code, sector, app_version) values (507, 'Zamit', 7, 'BBC', 'n/a', '0.7.9');
insert into project (id, name, service_provider_id, code, sector, app_version) values (508, 'Quo Lux', 8, 'WFC^', 'n/a', '0.4.7');
insert into project (id, name, service_provider_id, code, sector, app_version) values (509, 'Overhold', 9, 'STKS', 'Consumer Services', '0.1.9');
insert into project (id, name, service_provider_id, code, sector, app_version) values (510, 'Quo Lux', 10, 'ITCI', 'Health Care', '7.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (511, 'Alphazap', 11, 'ALSK', 'Public Utilities', '0.9.8');
insert into project (id, name, service_provider_id, code, sector, app_version) values (512, 'Zontrax', 12, 'WTW', 'Consumer Services', '0.76');
insert into project (id, name, service_provider_id, code, sector, app_version) values (513, 'Bigtax', 13, 'FTA', 'n/a', '0.9.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (514, 'Job', 14, 'ONVI', 'Miscellaneous', '1.21');
insert into project (id, name, service_provider_id, code, sector, app_version) values (515, 'Span', 15, 'STMP', 'Miscellaneous', '1.6.1');
insert into project (id, name, service_provider_id, code, sector, app_version) values (516, 'Toughjoyfax', 16, 'XLNX', 'Technology', '0.3.8');
insert into project (id, name, service_provider_id, code, sector, app_version) values (517, 'Fintone', 17, 'ACTX', 'n/a', '8.9.7');
insert into project (id, name, service_provider_id, code, sector, app_version) values (518, 'Mat Lam Tam', 18, 'KONE', 'Technology', '2.18');
insert into project (id, name, service_provider_id, code, sector, app_version) values (519, 'Ronstring', 19, 'CLRB', 'Health Care', '8.8');
insert into project (id, name, service_provider_id, code, sector, app_version) values (520, 'Matsoft', 20, 'OPXA', 'Health Care', '7.01');
insert into project (id, name, service_provider_id, code, sector, app_version) values (521, 'Ronstring', 21, 'FORT', 'Technology', '4.92');
insert into project (id, name, service_provider_id, code, sector, app_version) values (522, 'Quo Lux', 22, 'BCO', 'Transportation', '1.9');
insert into project (id, name, service_provider_id, code, sector, app_version) values (523, 'Sonsing', 23, 'SGYP', 'Health Care', '7.0.7');
insert into project (id, name, service_provider_id, code, sector, app_version) values (524, 'Transcof', 24, 'SGMO', 'Health Care', '0.22');
insert into project (id, name, service_provider_id, code, sector, app_version) values (525, 'Cardify', 25, 'BTEC', 'n/a', '4.19');
insert into project (id, name, service_provider_id, code, sector, app_version) values (526, 'Mat Lam Tam', 26, 'ANCX', 'Finance', '0.4.9');
insert into project (id, name, service_provider_id, code, sector, app_version) values (527, 'Zontrax', 27, 'VCO', 'Consumer Non-Durables', '8.8.1');
insert into project (id, name, service_provider_id, code, sector, app_version) values (528, 'Overhold', 28, 'PBI', 'Miscellaneous', '6.9');
insert into project (id, name, service_provider_id, code, sector, app_version) values (529, 'Cookley', 29, 'OMEX', 'Consumer Services', '9.1.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (530, 'Zontrax', 30, 'OXBR', 'Finance', '9.68');
insert into project (id, name, service_provider_id, code, sector, app_version) values (531, 'Gembucket', 31, 'SRSC', 'Consumer Services', '0.58');
insert into project (id, name, service_provider_id, code, sector, app_version) values (532, 'Gembucket', 32, 'JOUT', 'Consumer Non-Durables', '7.1.1');
insert into project (id, name, service_provider_id, code, sector, app_version) values (533, 'Transcof', 33, 'INTC', 'Technology', '9.1.9');
insert into project (id, name, service_provider_id, code, sector, app_version) values (534, 'Mat Lam Tam', 34, 'AIZ', 'Finance', '8.45');
insert into project (id, name, service_provider_id, code, sector, app_version) values (535, 'Keylex', 35, 'GOVN', 'Finance', '0.1.4');
insert into project (id, name, service_provider_id, code, sector, app_version) values (536, 'Transcof', 36, 'APOG', 'Capital Goods', '4.1.8');
insert into project (id, name, service_provider_id, code, sector, app_version) values (537, 'Fintone', 37, 'PER', 'Energy', '7.12');
insert into project (id, name, service_provider_id, code, sector, app_version) values (538, 'Trippledex', 38, 'HYLS', 'n/a', '0.95');
insert into project (id, name, service_provider_id, code, sector, app_version) values (539, 'Home Ing', 39, 'CAI', 'Technology', '3.4.1');
insert into project (id, name, service_provider_id, code, sector, app_version) values (540, 'Ventosanzap', 40, 'MUH', 'n/a', '3.1');
insert into project (id, name, service_provider_id, code, sector, app_version) values (541, 'Sonair', 41, 'TRK', 'Consumer Services', '4.3.9');
insert into project (id, name, service_provider_id, code, sector, app_version) values (542, 'Holdlamis', 42, 'SAUC', 'Consumer Services', '0.66');
insert into project (id, name, service_provider_id, code, sector, app_version) values (543, 'Fintone', 43, 'TPX', 'Consumer Durables', '8.7.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (544, 'Flowdesk', 44, 'FNTE', 'Finance', '1.16');
insert into project (id, name, service_provider_id, code, sector, app_version) values (545, 'Konklux', 45, 'CYTK', 'Health Care', '0.70');
insert into project (id, name, service_provider_id, code, sector, app_version) values (546, 'Lotlux', 46, 'TDA', 'Public Utilities', '9.00');
insert into project (id, name, service_provider_id, code, sector, app_version) values (547, 'Zamit', 47, 'SGMS', 'Technology', '0.56');
insert into project (id, name, service_provider_id, code, sector, app_version) values (548, 'Flexidy', 48, 'CATO', 'Consumer Services', '0.6.1');
insert into project (id, name, service_provider_id, code, sector, app_version) values (549, 'Subin', 49, 'OLBK', 'Finance', '0.9.7');
insert into project (id, name, service_provider_id, code, sector, app_version) values (550, 'Redhold', 50, 'SGY', 'Energy', '4.1.8');
insert into project (id, name, service_provider_id, code, sector, app_version) values (551, 'Daltfresh', 51, 'AEO', 'Consumer Services', '0.92');
insert into project (id, name, service_provider_id, code, sector, app_version) values (552, 'Bigtax', 52, 'BDXA', 'Health Care', '2.5');
insert into project (id, name, service_provider_id, code, sector, app_version) values (553, 'Sonsing', 53, 'NX', 'Capital Goods', '2.72');
insert into project (id, name, service_provider_id, code, sector, app_version) values (554, 'Stringtough', 54, 'MAGS', 'Consumer Durables', '6.0');
insert into project (id, name, service_provider_id, code, sector, app_version) values (555, 'Sonsing', 55, 'LMRK', 'Consumer Services', '0.1.9');
insert into project (id, name, service_provider_id, code, sector, app_version) values (556, 'Trippledex', 56, 'MYOV', 'Health Care', '5.51');
insert into project (id, name, service_provider_id, code, sector, app_version) values (557, 'Kanlam', 57, 'BAC^', 'n/a', '1.7.1');
insert into project (id, name, service_provider_id, code, sector, app_version) values (558, 'Stringtough', 58, 'HIE', 'n/a', '9.6.0');
insert into project (id, name, service_provider_id, code, sector, app_version) values (559, 'Bytecard', 59, 'VIV', 'Public Utilities', '0.69');
insert into project (id, name, service_provider_id, code, sector, app_version) values (560, 'Cardguard', 60, 'CTRP', 'Miscellaneous', '8.6.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (561, 'Asoka', 61, 'VIV', 'Public Utilities', '9.68');
insert into project (id, name, service_provider_id, code, sector, app_version) values (562, 'Tin', 62, 'LPX', 'Basic Industries', '0.34');
insert into project (id, name, service_provider_id, code, sector, app_version) values (563, 'Voyatouch', 63, 'MSP', 'n/a', '8.17');
insert into project (id, name, service_provider_id, code, sector, app_version) values (564, 'Home Ing', 64, 'PNTR', 'Technology', '0.24');
insert into project (id, name, service_provider_id, code, sector, app_version) values (565, 'Alphazap', 65, 'GPP', 'Basic Industries', '0.3.0');
insert into project (id, name, service_provider_id, code, sector, app_version) values (566, 'Latlux', 66, 'CG', 'Finance', '5.7');
insert into project (id, name, service_provider_id, code, sector, app_version) values (567, 'Y-Solowarm', 67, 'NOVN', 'Health Care', '3.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (568, 'Voltsillam', 68, 'MNKD', 'Health Care', '0.6.9');
insert into project (id, name, service_provider_id, code, sector, app_version) values (569, 'Andalax', 69, 'PHM', 'Capital Goods', '3.5.1');
insert into project (id, name, service_provider_id, code, sector, app_version) values (570, 'Bigtax', 70, 'PSA^', 'n/a', '2.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (571, 'Konklab', 71, 'SYNA', 'Technology', '0.9.4');
insert into project (id, name, service_provider_id, code, sector, app_version) values (572, 'Tin', 72, 'FWON', 'Consumer Services', '4.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (573, 'Voyatouch', 73, 'LFGR', 'Technology', '8.89');
insert into project (id, name, service_provider_id, code, sector, app_version) values (574, 'Solarbreeze', 74, 'LVHD', 'n/a', '5.39');
insert into project (id, name, service_provider_id, code, sector, app_version) values (575, 'Tres-Zap', 75, 'IRIX', 'Health Care', '1.6');
insert into project (id, name, service_provider_id, code, sector, app_version) values (576, 'Sub-Ex', 76, 'UBS', 'Finance', '0.6.5');
insert into project (id, name, service_provider_id, code, sector, app_version) values (577, 'Stringtough', 77, 'RYAM', 'Basic Industries', '6.9.8');
insert into project (id, name, service_provider_id, code, sector, app_version) values (578, 'Bigtax', 78, 'CBPO', 'Health Care', '9.05');
insert into project (id, name, service_provider_id, code, sector, app_version) values (579, 'Voltsillam', 79, 'NYCB', 'Finance', '0.3.5');
insert into project (id, name, service_provider_id, code, sector, app_version) values (580, 'Fix San', 80, 'FONR', 'Health Care', '1.7.1');
insert into project (id, name, service_provider_id, code, sector, app_version) values (581, 'Lotstring', 81, 'BYD', 'Consumer Services', '0.71');
insert into project (id, name, service_provider_id, code, sector, app_version) values (582, 'Otcom', 82, 'WHLR', 'Consumer Services', '0.4.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (583, 'Rank', 83, 'CAF', 'n/a', '7.66');
insert into project (id, name, service_provider_id, code, sector, app_version) values (584, 'Bitchip', 84, 'PPR', 'n/a', '0.27');
insert into project (id, name, service_provider_id, code, sector, app_version) values (585, 'Solarbreeze', 85, 'TTC', 'Capital Goods', '0.52');
insert into project (id, name, service_provider_id, code, sector, app_version) values (586, 'Zontrax', 86, 'GLBL', 'Public Utilities', '5.5');
insert into project (id, name, service_provider_id, code, sector, app_version) values (587, 'Stringtough', 87, 'BFZ', 'n/a', '1.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (588, 'Zaam-Dox', 88, 'GALT', 'Health Care', '0.3.7');
insert into project (id, name, service_provider_id, code, sector, app_version) values (589, 'Ronstring', 89, 'EACQ', 'Capital Goods', '3.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (590, 'Regrant', 90, 'IVEN', 'n/a', '2.95');
insert into project (id, name, service_provider_id, code, sector, app_version) values (591, 'Wrapsafe', 91, 'RPAI', 'n/a', '6.3');
insert into project (id, name, service_provider_id, code, sector, app_version) values (592, 'Greenlam', 92, 'BSL', 'n/a', '7.0.8');
insert into project (id, name, service_provider_id, code, sector, app_version) values (593, 'Viva', 93, 'WSFS', 'Finance', '6.70');
insert into project (id, name, service_provider_id, code, sector, app_version) values (594, 'Flexidy', 94, 'BIDU', 'Technology', '0.94');
insert into project (id, name, service_provider_id, code, sector, app_version) values (595, 'Alpha', 95, 'STAR', 'Consumer Services', '0.5.4');
insert into project (id, name, service_provider_id, code, sector, app_version) values (596, 'Matsoft', 96, 'MMDM', 'Finance', '6.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (597, 'Holdlamis', 97, 'NX', 'Capital Goods', '7.1');
insert into project (id, name, service_provider_id, code, sector, app_version) values (598, 'Bytecard', 98, 'CMG', 'Consumer Services', '1.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (599, 'Aerified', 99, 'BBU', 'Basic Industries', '4.6.2');
insert into project (id, name, service_provider_id, code, sector, app_version) values (600, 'Quo Lux', 100, 'TAST', 'Consumer Services', '0.71');
